### ISSUE TITLE
undefined reference to `notmuch_database_get_revision' etc

### ISSUE THREAD

**Issue by airways** [astroidmail/astroid#356]
Getting further along in the build on Ubuntu 14.04 after downloading GMime-2.6.gir from an arch package (added a note to #211 on how I did this), now I get this error during linking. This is with notmuch 0.24.

```
iraway@OCULAR:~/workspace/astroid$ scons --disable-libsass --scss-compiler=../sassc/bin/sassc
scons: Reading SConscript files ...
building version v0.9.1-13-g2240ef5c (git)..
debug flag enabled: True
Checking for pkg-config... (cached) yes
Checking for gtkmm-3.0 >= 3.10... (cached) yes
Checking for glibmm-2.4... (cached) yes
Checking for gmime-2.6 >= 2.6.18... (cached) yes
Checking for webkitgtk-3.0... (cached) yes
Checking for vte-2.91... (cached) no
warning: vte3 not found: disabling built-in terminal.
warning: built-in terminal disabled.
warning: libsass is disabled, will generate SCSS at build time using: '../sassc/bin/sassc'..
Checking for gobject-introspection-1.0... (cached) yes
Checking for libpeas-1.0... (cached) yes
Checking for C library notmuch... (cached) yes
Checking for C++ library boost_filesystem... (cached) yes
Checking for C++ library boost_system... (cached) yes
Checking for C++ library boost_program_options... (cached) yes
Checking for C++ library boost_log_setup... (cached) yes
Checking for C++ library boost_log... (cached) yes
Checking for C++ library boost_thread... (cached) yes
Checking for C++ library boost_date_time... (cached) yes
writing src/build_config.hh..

    debug   ..:  True
    release ..:  git
    version ..:  v0.9.1-13-g2240ef5c
    profile ..:  False
    libsass ..:  False
    scss .....:  ../sassc/bin/sassc ( use: True )
    plugins ..:  True
    terminal .:  False
    embedded .:  True
    prefix ...:  /usr/local

scons: done reading SConscript files.
scons: Building targets ...
LD_LIBRARY_PATH=./ g-ir-scanner -o Astroid-0.1.gir --warn-all --namespace=Astroid --include=GObject-2.0 --include=GMime-2.6 --nsversion=0.1 --pkg=gobject-introspection-1.0 --pkg=gmime-2.6 -Isrc/ --program=./girmain src/plugin/astroid_activatable.c src/plugin/gir_main.c src/plugin/thread_index_activatable.c src/plugin/thread_view_activatable.c src/plugin/astroid_activatable.h src/plugin/thread_index_activatable.h src/plugin/thread_view_activatable.h
src/plugin/thread_index_activatable.c:93: Warning: Astroid: astroid_threadindex_activatable_format_tags: argument selected: Unresolved type: 'bool'
src/plugin/thread_view_activatable.c:146: Warning: Astroid: astroid_threadview_activatable_format_tags: argument selected: Unresolved type: 'bool'
g-ir-compiler -o Astroid-0.1.typelib Astroid-0.1.gir
linking Program ==> astroid
src/db.o: In function `Astroid::Db::get_revision()':
/home/iraway/workspace/astroid/src/db.cc:233: undefined reference to `notmuch_database_get_revision'
src/db.o: In function `Astroid::Db::thread_in_query(Glib::ustring, Glib::ustring)':
/home/iraway/workspace/astroid/src/db.cc:353: undefined reference to `notmuch_query_count_threads_st'
src/db.o: In function `Astroid::Db::on_thread(Glib::ustring, std::function<void (_notmuch_thread*)>)':
/home/iraway/workspace/astroid/src/db.cc:377: undefined reference to `notmuch_query_search_threads_st'
src/poll.o: In function `Astroid::Poll::refresh_threads()':
/home/iraway/workspace/astroid/src/poll.cc:339: undefined reference to `notmuch_query_count_threads_st'
/home/iraway/workspace/astroid/src/poll.cc:346: undefined reference to `notmuch_query_search_threads_st'
src/modes/saved_searches.o: In function `Astroid::SavedSearches::refresh_stats_db(Astroid::Db*)':
/home/iraway/workspace/astroid/src/modes/saved_searches.cc:448: undefined reference to `notmuch_query_count_messages_st'
/home/iraway/workspace/astroid/src/modes/saved_searches.cc:458: undefined reference to `notmuch_query_count_messages_st'
src/modes/thread_index/query_loader.o: In function `Astroid::QueryLoader::refresh_stats_db(Astroid::Db*)':
/home/iraway/workspace/astroid/src/modes/thread_index/query_loader.cc:112: undefined reference to `notmuch_query_count_messages_st'
/home/iraway/workspace/astroid/src/modes/thread_index/query_loader.cc:122: undefined reference to `notmuch_query_count_messages_st'
src/modes/thread_index/query_loader.o: In function `Astroid::QueryLoader::loader()':
/home/iraway/workspace/astroid/src/modes/thread_index/query_loader.cc:151: undefined reference to `notmuch_query_search_threads_st'
collect2: error: ld returned 1 exit status
scons: *** [astroid] Error 1
scons: building terminated because of errors.
```

**Comment by airways** [comment]
Trying a rebuild after running a clean with:

```
scons -c --disable-libsass --scss-compiler=../sassc/bin/sassc
```

This seems to have still failed. I thought it was probably due to previously having an old notmuch provided by Ubuntu which failed to build and has been removed in favor of a version installed from source, but now I am not sure. Any ideas?

```
iraway@OCULAR:~/workspace/astroid$ scons --disable-libsass --scss-compiler=../sassc/bin/sassc
scons: Reading SConscript files ...
building version v0.9.1-13-g2240ef5c (git)..
debug flag enabled: True
Checking for pkg-config... (cached) yes
Checking for gtkmm-3.0 >= 3.10... (cached) yes
Checking for glibmm-2.4... (cached) yes
Checking for gmime-2.6 >= 2.6.18... (cached) yes
Checking for webkitgtk-3.0... (cached) yes
Checking for vte-2.91... (cached) no
warning: vte3 not found: disabling built-in terminal.
warning: built-in terminal disabled.
warning: libsass is disabled, will generate SCSS at build time using: '../sassc/bin/sassc'..
Checking for gobject-introspection-1.0... (cached) yes
Checking for libpeas-1.0... (cached) yes
Checking for C library notmuch... (cached) yes
Checking for C++ library boost_filesystem... (cached) yes
Checking for C++ library boost_system... (cached) yes
Checking for C++ library boost_program_options... (cached) yes
Checking for C++ library boost_log_setup... (cached) yes
Checking for C++ library boost_log... (cached) yes
Checking for C++ library boost_thread... (cached) yes
Checking for C++ library boost_date_time... (cached) yes
writing src/build_config.hh..

    debug   ..:  True
    release ..:  git
    version ..:  v0.9.1-13-g2240ef5c
    profile ..:  False
    libsass ..:  False
    scss .....:  ../sassc/bin/sassc ( use: True )
    plugins ..:  True
    terminal .:  False
    embedded .:  True
    prefix ...:  /usr/local

scons: done reading SConscript files.
scons: Building targets ...
compiling ==> src/main.cc
compiling ==> src/account_manager.cc
compiling ==> src/astroid.cc
compiling ==> src/chunk.cc
compiling ==> src/command_bar.cc
compiling ==> src/compose_message.cc
compiling ==> src/config.cc
compiling ==> src/crypto.cc
compiling ==> src/db.cc
compiling ==> src/main_window.cc
compiling ==> src/message_thread.cc
compiling ==> src/poll.cc
compiling ==> src/modes/edit_message.cc
compiling ==> src/modes/forward_message.cc
compiling ==> src/modes/help_mode.cc
compiling ==> src/modes/keybindings.cc
compiling ==> src/modes/log_view.cc
compiling ==> src/modes/mode.cc
compiling ==> src/modes/paned_mode.cc
compiling ==> src/modes/raw_message.cc
compiling ==> src/modes/reply_message.cc
compiling ==> src/modes/saved_searches.cc
compiling ==> src/modes/thread_index/query_loader.cc
compiling ==> src/modes/thread_index/thread_index.cc
compiling ==> src/modes/thread_index/thread_index_list_cell_renderer.cc
compiling ==> src/modes/thread_index/thread_index_list_view.cc
compiling ==> src/modes/thread_view/dom_utils.cc
compiling ==> src/modes/thread_view/theme.cc
compiling ==> src/modes/thread_view/thread_view.cc
compiling ==> src/modes/thread_view/web_inspector.cc
compiling ==> src/modes/editor/editor.cc
compiling ==> src/modes/editor/external.cc
compiling ==> src/modes/editor/plugin.cc
compiling ==> src/actions/action.cc
compiling ==> src/actions/action_manager.cc
compiling ==> src/actions/cmdaction.cc
compiling ==> src/actions/difftag_action.cc
compiling ==> src/actions/onmessage.cc
compiling ==> src/actions/tag_action.cc
compiling ==> src/actions/toggle_action.cc
compiling ==> src/utils/address.cc
compiling ==> src/utils/cmd.cc
compiling ==> src/utils/date_utils.cc
compiling ==> src/utils/gravatar.cc
compiling ==> src/utils/resource.cc
compiling ==> src/utils/ustring_utils.cc
compiling ==> src/utils/utils.cc
compiling ==> src/utils/vector_utils.cc
compiling ==> src/plugin/manager.cc
compiling ==> src/utils/gmime/gmime-filter-html-bq.c
compiling ==> src/utils/gmime/gtrie.c
compiling ==> src/utils/gmime/url-scanner.c
compiling ==> src/plugin/astroid_activatable.c
compiling ==> src/plugin/thread_index_activatable.c
compiling ==> src/plugin/thread_view_activatable.c
../sassc/bin/sassc ui/thread-view.scss ui/thread-view.css
compiling ==> src/plugin/gir_main.c
linking Program ==> girmain
LD_LIBRARY_PATH=./ g-ir-scanner -o Astroid-0.1.gir --warn-all --namespace=Astroid --include=GObject-2.0 --include=GMime-2.6 --nsversion=0.1 --pkg=gobject-introspection-1.0 --pkg=gmime-2.6 -Isrc/ --program=./girmain src/plugin/astroid_activatable.c src/plugin/gir_main.c src/plugin/thread_index_activatable.c src/plugin/thread_view_activatable.c src/plugin/astroid_activatable.h src/plugin/thread_index_activatable.h src/plugin/thread_view_activatable.h
src/plugin/thread_index_activatable.c:93: Warning: Astroid: astroid_threadindex_activatable_format_tags: argument selected: Unresolved type: 'bool'
src/plugin/thread_view_activatable.c:146: Warning: Astroid: astroid_threadview_activatable_format_tags: argument selected: Unresolved type: 'bool'
g-ir-compiler -o Astroid-0.1.typelib Astroid-0.1.gir
linking Program ==> astroid
src/db.o: In function `Astroid::Db::get_revision()':
/home/iraway/workspace/astroid/src/db.cc:233: undefined reference to `notmuch_database_get_revision'
src/db.o: In function `Astroid::Db::thread_in_query(Glib::ustring, Glib::ustring)':
/home/iraway/workspace/astroid/src/db.cc:353: undefined reference to `notmuch_query_count_threads_st'
src/db.o: In function `Astroid::Db::on_thread(Glib::ustring, std::function<void (_notmuch_thread*)>)':
/home/iraway/workspace/astroid/src/db.cc:377: undefined reference to `notmuch_query_search_threads_st'
src/poll.o: In function `Astroid::Poll::refresh_threads()':
/home/iraway/workspace/astroid/src/poll.cc:339: undefined reference to `notmuch_query_count_threads_st'
/home/iraway/workspace/astroid/src/poll.cc:346: undefined reference to `notmuch_query_search_threads_st'
src/modes/saved_searches.o: In function `Astroid::SavedSearches::refresh_stats_db(Astroid::Db*)':
/home/iraway/workspace/astroid/src/modes/saved_searches.cc:448: undefined reference to `notmuch_query_count_messages_st'
/home/iraway/workspace/astroid/src/modes/saved_searches.cc:458: undefined reference to `notmuch_query_count_messages_st'
src/modes/thread_index/query_loader.o: In function `Astroid::QueryLoader::refresh_stats_db(Astroid::Db*)':
/home/iraway/workspace/astroid/src/modes/thread_index/query_loader.cc:112: undefined reference to `notmuch_query_count_messages_st'
/home/iraway/workspace/astroid/src/modes/thread_index/query_loader.cc:122: undefined reference to `notmuch_query_count_messages_st'
src/modes/thread_index/query_loader.o: In function `Astroid::QueryLoader::loader()':
/home/iraway/workspace/astroid/src/modes/thread_index/query_loader.cc:151: undefined reference to `notmuch_query_search_threads_st'
collect2: error: ld returned 1 exit status
scons: *** [astroid] Error 1
scons: building terminated because of errors.
```

**Comment by airways** [comment]
Found another notmuch.h. Trying a second clean and build...

**Comment by airways** [comment]
Similar errors:

```
iraway@OCULAR:~/workspace/astroid$ scons -c --disable-libsass --scss-compiler=../sassc/bin/sassc
scons: Reading SConscript files ...
building version v0.9.1-13-g2240ef5c (git)..
debug flag enabled: True
Checking for pkg-config... (cached) yes
Checking for gtkmm-3.0 >= 3.10... (cached) yes
Checking for glibmm-2.4... (cached) yes
Checking for gmime-2.6 >= 2.6.18... (cached) yes
Checking for webkitgtk-3.0... (cached) yes
Checking for vte-2.91... (cached) no
warning: vte3 not found: disabling built-in terminal.
warning: built-in terminal disabled.
warning: libsass is disabled, will generate SCSS at build time using: '../sassc/bin/sassc'..
Checking for gobject-introspection-1.0... (cached) yes
Checking for libpeas-1.0... (cached) yes
Checking for C library notmuch... (cached) yes
Checking for C++ library boost_filesystem... (cached) yes
Checking for C++ library boost_system... (cached) yes
Checking for C++ library boost_program_options... (cached) yes
Checking for C++ library boost_log_setup... (cached) yes
Checking for C++ library boost_log... (cached) yes
Checking for C++ library boost_thread... (cached) yes
Checking for C++ library boost_date_time... (cached) yes
writing src/build_config.hh..

    debug   ..:  True
    release ..:  git
    version ..:  v0.9.1-13-g2240ef5c
    profile ..:  False
    libsass ..:  False
    scss .....:  ../sassc/bin/sassc ( use: True )
    plugins ..:  True
    terminal .:  False
    embedded .:  True
    prefix ...:  /usr/local

scons: done reading SConscript files.
scons: Cleaning targets ...
Removed src/main.o
Removed src/account_manager.o
Removed src/astroid.o
Removed src/chunk.o
Removed src/command_bar.o
Removed src/compose_message.o
Removed src/config.o
Removed src/crypto.o
Removed src/db.o
Removed src/main_window.o
Removed src/message_thread.o
Removed src/poll.o
Removed src/modes/edit_message.o
Removed src/modes/forward_message.o
Removed src/modes/help_mode.o
Removed src/modes/keybindings.o
Removed src/modes/log_view.o
Removed src/modes/mode.o
Removed src/modes/paned_mode.o
Removed src/modes/raw_message.o
Removed src/modes/reply_message.o
Removed src/modes/saved_searches.o
Removed src/modes/thread_index/query_loader.o
Removed src/modes/thread_index/thread_index.o
Removed src/modes/thread_index/thread_index_list_cell_renderer.o
Removed src/modes/thread_index/thread_index_list_view.o
Removed src/modes/thread_view/dom_utils.o
Removed src/modes/thread_view/theme.o
Removed src/modes/thread_view/thread_view.o
Removed src/modes/thread_view/web_inspector.o
Removed src/modes/editor/editor.o
Removed src/modes/editor/external.o
Removed src/modes/editor/plugin.o
Removed src/actions/action.o
Removed src/actions/action_manager.o
Removed src/actions/cmdaction.o
Removed src/actions/difftag_action.o
Removed src/actions/onmessage.o
Removed src/actions/tag_action.o
Removed src/actions/toggle_action.o
Removed src/utils/address.o
Removed src/utils/cmd.o
Removed src/utils/date_utils.o
Removed src/utils/gravatar.o
Removed src/utils/resource.o
Removed src/utils/ustring_utils.o
Removed src/utils/utils.o
Removed src/utils/vector_utils.o
Removed src/plugin/manager.o
Removed src/utils/gmime/gmime-filter-html-bq.o
Removed src/utils/gmime/gtrie.o
Removed src/utils/gmime/url-scanner.o
Removed src/plugin/astroid_activatable.o
Removed src/plugin/thread_index_activatable.o
Removed src/plugin/thread_view_activatable.o
Removed ui/thread-view.css
Removed src/plugin/gir_main.o
Removed girmain
Removed Astroid-0.1.gir
Removed Astroid-0.1.typelib
scons: done cleaning targets.
iraway@OCULAR:~/workspace/astroid$ scons --disable-libsass --scss-compiler=../sassc/bin/sassc
scons: Reading SConscript files ...
building version v0.9.1-13-g2240ef5c (git)..
debug flag enabled: True
Checking for pkg-config... (cached) yes
Checking for gtkmm-3.0 >= 3.10... (cached) yes
Checking for glibmm-2.4... (cached) yes
Checking for gmime-2.6 >= 2.6.18... (cached) yes
Checking for webkitgtk-3.0... (cached) yes
Checking for vte-2.91... (cached) no
warning: vte3 not found: disabling built-in terminal.
warning: built-in terminal disabled.
warning: libsass is disabled, will generate SCSS at build time using: '../sassc/bin/sassc'..
Checking for gobject-introspection-1.0... (cached) yes
Checking for libpeas-1.0... (cached) yes
Checking for C library notmuch... (cached) yes
Checking for C++ library boost_filesystem... (cached) yes
Checking for C++ library boost_system... (cached) yes
Checking for C++ library boost_program_options... (cached) yes
Checking for C++ library boost_log_setup... (cached) yes
Checking for C++ library boost_log... (cached) yes
Checking for C++ library boost_thread... (cached) yes
Checking for C++ library boost_date_time... (cached) yes
writing src/build_config.hh..

    debug   ..:  True
    release ..:  git
    version ..:  v0.9.1-13-g2240ef5c
    profile ..:  False
    libsass ..:  False
    scss .....:  ../sassc/bin/sassc ( use: True )
    plugins ..:  True
    terminal .:  False
    embedded .:  True
    prefix ...:  /usr/local

scons: done reading SConscript files.
scons: Building targets ...
compiling ==> src/main.cc
compiling ==> src/account_manager.cc
compiling ==> src/astroid.cc
compiling ==> src/chunk.cc
compiling ==> src/command_bar.cc
compiling ==> src/compose_message.cc
compiling ==> src/config.cc
compiling ==> src/crypto.cc
compiling ==> src/db.cc
compiling ==> src/main_window.cc
compiling ==> src/message_thread.cc
compiling ==> src/poll.cc
compiling ==> src/modes/edit_message.cc
compiling ==> src/modes/forward_message.cc
compiling ==> src/modes/help_mode.cc
compiling ==> src/modes/keybindings.cc
compiling ==> src/modes/log_view.cc
compiling ==> src/modes/mode.cc
compiling ==> src/modes/paned_mode.cc
compiling ==> src/modes/raw_message.cc
compiling ==> src/modes/reply_message.cc
compiling ==> src/modes/saved_searches.cc
compiling ==> src/modes/thread_index/query_loader.cc
compiling ==> src/modes/thread_index/thread_index.cc
compiling ==> src/modes/thread_index/thread_index_list_cell_renderer.cc
compiling ==> src/modes/thread_index/thread_index_list_view.cc
compiling ==> src/modes/thread_view/dom_utils.cc
compiling ==> src/modes/thread_view/theme.cc
compiling ==> src/modes/thread_view/thread_view.cc
compiling ==> src/modes/thread_view/web_inspector.cc
compiling ==> src/modes/editor/editor.cc
compiling ==> src/modes/editor/external.cc
compiling ==> src/modes/editor/plugin.cc
compiling ==> src/actions/action.cc
compiling ==> src/actions/action_manager.cc
compiling ==> src/actions/cmdaction.cc
compiling ==> src/actions/difftag_action.cc
compiling ==> src/actions/onmessage.cc
compiling ==> src/actions/tag_action.cc
compiling ==> src/actions/toggle_action.cc
compiling ==> src/utils/address.cc
compiling ==> src/utils/cmd.cc
compiling ==> src/utils/date_utils.cc
compiling ==> src/utils/gravatar.cc
compiling ==> src/utils/resource.cc
compiling ==> src/utils/ustring_utils.cc
compiling ==> src/utils/utils.cc
compiling ==> src/utils/vector_utils.cc
compiling ==> src/plugin/manager.cc
compiling ==> src/utils/gmime/gmime-filter-html-bq.c
compiling ==> src/utils/gmime/gtrie.c
compiling ==> src/utils/gmime/url-scanner.c
compiling ==> src/plugin/astroid_activatable.c
compiling ==> src/plugin/thread_index_activatable.c
compiling ==> src/plugin/thread_view_activatable.c
../sassc/bin/sassc ui/thread-view.scss ui/thread-view.css
compiling ==> src/plugin/gir_main.c
linking Program ==> girmain
LD_LIBRARY_PATH=./ g-ir-scanner -o Astroid-0.1.gir --warn-all --namespace=Astroid --include=GObject-2.0 --include=GMime-2.6 --nsversion=0.1 --pkg=gobject-introspection-1.0 --pkg=gmime-2.6 -Isrc/ --program=./girmain src/plugin/astroid_activatable.c src/plugin/gir_main.c src/plugin/thread_index_activatable.c src/plugin/thread_view_activatable.c src/plugin/astroid_activatable.h src/plugin/thread_index_activatable.h src/plugin/thread_view_activatable.h
src/plugin/thread_index_activatable.c:93: Warning: Astroid: astroid_threadindex_activatable_format_tags: argument selected: Unresolved type: 'bool'
src/plugin/thread_view_activatable.c:146: Warning: Astroid: astroid_threadview_activatable_format_tags: argument selected: Unresolved type: 'bool'
g-ir-compiler -o Astroid-0.1.typelib Astroid-0.1.gir
linking Program ==> astroid
src/db.o: In function `Astroid::Db::get_revision()':
/home/iraway/workspace/astroid/src/db.cc:233: undefined reference to `notmuch_database_get_revision'
src/db.o: In function `Astroid::Db::thread_in_query(Glib::ustring, Glib::ustring)':
/home/iraway/workspace/astroid/src/db.cc:353: undefined reference to `notmuch_query_count_threads_st'
src/db.o: In function `Astroid::Db::on_thread(Glib::ustring, std::function<void (_notmuch_thread*)>)':
/home/iraway/workspace/astroid/src/db.cc:377: undefined reference to `notmuch_query_search_threads_st'
src/poll.o: In function `Astroid::Poll::refresh_threads()':
/home/iraway/workspace/astroid/src/poll.cc:339: undefined reference to `notmuch_query_count_threads_st'
/home/iraway/workspace/astroid/src/poll.cc:346: undefined reference to `notmuch_query_search_threads_st'
src/modes/saved_searches.o: In function `Astroid::SavedSearches::refresh_stats_db(Astroid::Db*)':
/home/iraway/workspace/astroid/src/modes/saved_searches.cc:448: undefined reference to `notmuch_query_count_messages_st'
/home/iraway/workspace/astroid/src/modes/saved_searches.cc:458: undefined reference to `notmuch_query_count_messages_st'
src/modes/thread_index/query_loader.o: In function `Astroid::QueryLoader::refresh_stats_db(Astroid::Db*)':
/home/iraway/workspace/astroid/src/modes/thread_index/query_loader.cc:112: undefined reference to `notmuch_query_count_messages_st'
/home/iraway/workspace/astroid/src/modes/thread_index/query_loader.cc:122: undefined reference to `notmuch_query_count_messages_st'
src/modes/thread_index/query_loader.o: In function `Astroid::QueryLoader::loader()':
/home/iraway/workspace/astroid/src/modes/thread_index/query_loader.cc:151: undefined reference to `notmuch_query_search_threads_st'
collect2: error: ld returned 1 exit status
scons: *** [astroid] Error 1
scons: building terminated because of errors.
```

**Comment by airways** [comment]
I found a rougue notmuch.a that needed to be moved away as well, under /usr/lib. astroid is now running on my system! Though there are many apparent bugs and it is not quite usable yet, this is progress.

**Comment by gauteh** [comment]
Isaac Raway writes on mai 26, 2017 3:25:
> I found a rougue notmuch.a that needed to be moved away as well, under /usr/lib. astroid is now running on my system! Though there are many apparent bugs and it is not quite usable yet, this is progress.

Good!
