### ISSUE TITLE
error: 'notmuch_database_get_revision' was not declared in this scope

### ISSUE THREAD

**Issue by airways** [astroidmail/astroid#352]
Attempting to build on Ubuntu 14.04 I get the following error:

```
iraway@OCULAR:~/workspace/astroid$ scons --disable-libsass
scons: Reading SConscript files ...
building version v0.9.1-8-gf98d4caf (git)..
debug flag enabled: True
Checking for pkg-config... yes
Checking for gtkmm-3.0 >= 3.10... yes
Checking for glibmm-2.4... yes
Checking for gmime-2.6 >= 2.6.18... yes
Checking for webkitgtk-3.0... yes
Checking for vte-2.91... no
warning: vte3 not found: disabling built-in terminal.
warning: built-in terminal disabled.
warning: libsass is disabled, will generate SCSS at build time using: 'sassc'..
Checking for gobject-introspection-1.0... yes
Checking for libpeas-1.0... yes
Checking for C library notmuch... yes
Checking for C++ library boost_filesystem... yes
Checking for C++ library boost_system... yes
Checking for C++ library boost_program_options... yes
Checking for C++ library boost_log_setup... yes
Checking for C++ library boost_log... yes
Checking for C++ library boost_thread... yes
Checking for C++ library boost_date_time... yes
writing src/build_config.hh..

    debug   ..:  True
    release ..:  git
    version ..:  v0.9.1-8-gf98d4caf
    profile ..:  False
    libsass ..:  False
    scss .....:  sassc ( use: True )
    plugins ..:  True
    terminal .:  False
    embedded .:  True
    prefix ...:  /usr/local

scons: done reading SConscript files.
scons: Building targets ...
compiling ==> src/main.cc
compiling ==> src/account_manager.cc
compiling ==> src/astroid.cc
compiling ==> src/chunk.cc
compiling ==> src/command_bar.cc
compiling ==> src/compose_message.cc
compiling ==> src/config.cc
compiling ==> src/crypto.cc
compiling ==> src/db.cc
src/db.cc: In member function 'long unsigned int Astroid::Db::get_revision()':
src/db.cc:233:73: error: 'notmuch_database_get_revision' was not declared in this scope
     unsigned long revision = notmuch_database_get_revision (nm_db, &uuid);
                                                                         ^
In file included from src/db.cc:17:0:
src/db.cc: In member function 'bool Astroid::Db::thread_in_query(Astroid::ustring, Astroid::ustring)':
src/db.hh:23:77: error: 'notmuch_query_count_threads_st' was not declared in this scope
 # define notmuch_query_count_threads(x,y) notmuch_query_count_threads_st(x,y)
                                                                             ^
src/db.cc:353:10: note: in expansion of macro 'notmuch_query_count_threads'
     st = notmuch_query_count_threads (query, &c);
          ^
src/db.cc: In member function 'void Astroid::Db::on_thread(Astroid::ustring, std::function<void(_notmuch_thread*)>)':
src/db.hh:22:79: error: 'notmuch_query_search_threads_st' was not declared in this scope
 # define notmuch_query_search_threads(x,y) notmuch_query_search_threads_st(x,y)
                                                                               ^
src/db.cc:377:10: note: in expansion of macro 'notmuch_query_search_threads'
     st = notmuch_query_search_threads (query, &nm_threads);
          ^
scons: *** [src/db.o] Error 1
scons: building terminated because of errors.
```

I see from #145 that support was extended to 15.10 after similar errors were encountered there. Is it possible to do the same for 14.04? Many users are still on this system and will likely remain so for at least 2 years. If not I can understand but it would be awesome if it is possible.

**Comment by gauteh** [comment]
Hi Isaac,

these errors result from using a quite old notmuch library. Is it
possible to upgrade?

- gaute

**Comment by gauteh** [comment]
I am going to close this one since it results from having an too old notmuch.

**Comment by airways** [comment]
Hi @gauteh this is the version of notmuch that ships with Ubuntu 14.04 LTS, which has support from Canonicalfor the next two years. Because of this, I suspect many users on this platform may try to install astroid and will not be able to do so.

The same underlying cause (old version of notmuch though I'm not sure what version) was fixed in ticket #145 for Ubuntu 15.10 even though (at the time that ticket was opened) it had only two months of support from Canonical left and now it's likely that few users will still be on that platform and expect to be able to install new software since they know they need to upgrade

To me it seems to me like a good use of time if it is possible to support this version of notmuch as it may attract many additional users.

For me, currently I cannot use a newer version of Ubuntu because this is the version that ships with Windows Subsystem for Linux and in this revision they do not support any other distros. After the Creator's Update I will likely upgrade, but many users will still be on Ubuntu 14.04 until 2019.

I can try installing not manually, and probably will do so today or this weekend, but I think this is still worth considering a fix for if you have the time since some users will not want to do this.

**Comment by gauteh** [comment]
Hi,

I think these are all good points - but at some point it gets really
tedious to support the various combinations of dependencies. Isn't
notmcuh backported to that Ubuntu version?

**Comment by airways** [comment]
When I install notmuch I get 0.17. Trying to find a reliable PPA that might be able to provide it but it seems perhaps installing from source would be the easiest route for me. I usually prefer that to using a PPA since it's difficult to be sure what third-parties might do to the source before publishing it.

**Comment by gauteh** [comment]
Isaac Raway writes on mai 25, 2017 18:37:
> When I install notmuch I get 0.17. Trying to find a reliable PPA that might be able to provide it but it seems perhaps installing from source would be the easiest route for me. I usually prefer that to using a PPA since it's difficult to be sure what third-parties might do to the source before publishing it.
> 

You might want to ask at #notmuch or at the notmuch mailing list for the
preferred option. I know core devs are on debian, so ubuntu support
should be good.

- gaute

**Comment by gauteh** [comment]
Latest notmuch is 0.24 here by the way, so this is faaar behind ;)
